library(plasma)
data("TCGA-ESCA")
MO <- prepareMultiOmics(assemble, Outcome)
fitted <- fitSingleModel(MO, "miRSeq", "Days", "vital_status", "dead")
summary(fitted)
plot(fitted, xlab = "Time (Days)", legloc = "topright", main = "Training Data")
p <- predict(fitted)
p <- try( predict(fitted, "risk") )
p <- try( predict(fitted, type = "riak") )
p <- predict(fitted, type = "risk")
q <- predict(fitted, type = "split")
plot(p, q)
